# Generated by Django 5.2.7 on 2025-11-27 16:01

import document.storage_backends
import document.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_address_users_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=document.storage_backends.PrivateMediaStorage(), upload_to=document.utils.private_profile_upload_to),
        ),
    ]
