# Generated by Django 5.2.7 on 2025-10-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=110, max_digits=10),
        ),
    ]
