# Generated by Django 5.2.7 on 2025-10-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_delivery_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
    ]
