# Generated by Django 5.2.7 on 2025-11-28 03:20

import document.storage_backends
import document.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productreview_review_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.ImageField(blank=True, null=True, storage=document.storage_backends.PublicMediaStorage(), upload_to=document.utils.public_upload_to),
        ),
    ]
